### ISSUE TITLE
RuntimeError: The size of tensor a (52) must match the size of tensor b (90) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Agnes-L** [kaist-amsg/LocalTransform#2]
Thank you very much for your outstanding work on open source. When I tried to reproduce the results according to the steps, I got this error "RuntimeError: The size of tensor a (52) must match the size of tensor b (90) at non-singleton dimension 2" when running "python Train.py -s True".  Have you encountered the same error and is there any way to solve this error? Thank you very much for your help!

**Comment by shuan4638** [comment]
I didn't meet this error before, and I am not sure which line did you encounter this error. Could you show me the error message? Thanks!

**Comment by Agnes-L** [comment]
Thank you so much for your reply! Here's the message that reported the error, thanks for your help!
![image](https://user-images.githubusercontent.com/64192323/197183653-22633208-bcc4-44e5-ad94-cd8a1cdef8cc.png)

**Comment by shuan4638** [comment]
Hi @Agnes-L, 

After checking the scripts again, I found this error is due to the mismatch of graph position matrix (gpm) and atom features. This is due to the wrong graph making code in dataset.py line 83 and line 140: `get_adm(Chem.MolFromSmiles(s1))`
it should include the reagent as well, that is `get_adm(mol)` instead.
That was my mistake. Thank you so much for pointing this out!

I will fix this line in a minute and you can pull this repo again or simply change that line by yourself.
After removing the built graph in `data/saved/graphs/`, running `Train.py -s True` again should work just fine.

Best,
Shuan

**Comment by Agnes-L** [comment]
Thank you so much for your answer! After following your guidance, the error was solved successfully. But then this error came up again. Have you ever encountered this before? Thank you so much for your help again!
![D9Y4~2C (4@3@0B_6W_)~E8](https://user-images.githubusercontent.com/64192323/197333537-c8ca123f-a487-4ac4-97a0-5b8827a7fddf.png)

**Comment by shuan4638** [comment]
I did not meet this error before.
I see the error comes from the different device between bond features (cpu) and weights (cuda).
Could you try out changing line 62 in model_utils.py from `bond_feats = g.ndata['h'][bonds.unsqueeze(1)].view(-1, feat_dim*2)` to `bond_feats = g.ndata['h'][bonds.unsqueeze(1)].view(-1, feat_dim*2).to(device)`?

**Comment by Agnes-L** [comment]
It worked! Thank you so much for your patience and help. Best wishes for you!
